# Copyright 1999-2022 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.17.0

EAPI=8

DIST_AUTHOR="PMQS"
DIST_VERSION="1.858"


inherit perl-module

DESCRIPTION="Perl5 access to Berkeley DB version 1.x"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64 ~x86 "
IUSE=""

DEPEND="dev-lang/perl"
