# Copyright 1999-2022 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.17.0

EAPI=8

DIST_AUTHOR="MMIMS"
DIST_VERSION="0.12008"


inherit perl-module

DESCRIPTION="A perl library for Twitter's API v1"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64 ~x86 "
IUSE=""

DEPEND="dev-perl/IO
	dev-perl/Test-Fatal
	>=dev-perl/JSON-4.30.0
	dev-perl/Module-Build
	virtual/perl-Encode
	>=dev-perl/Net-OAuth-0.280.0
	>=dev-perl/URI-5.110.0
	>=dev-perl/libwww-perl-6.600.0
	dev-perl/LWP-Protocol-https
	>=dev-perl/Net-HTTP-6.220.0
	dev-perl/Data-Dumper
	dev-perl/HTTP-Message
	dev-lang/perl"

BDEPEND="
	>=dev-perl/Mddodule-Build-Tiny-0.39.0
"
