# Copyright 1999-2022 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.17.0

EAPI=8

DIST_AUTHOR="NWCLARK"
DIST_VERSION="2.183"


inherit perl-module

DESCRIPTION="stringified perl data structures, suitable for both printing and C<eval>"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64 ~x86 "
IUSE=""

DEPEND="dev-lang/perl"
