# Copyright 1999-2022 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.17.0

EAPI=8

DIST_AUTHOR="ESAYM"
DIST_VERSION="1.3401"


inherit perl-module

DESCRIPTION="a simple API to convert seconds to other date values"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64 ~x86 "
IUSE=""

DEPEND="virtual/perl-Scalar-List-Utils
	dev-lang/perl"
