# Copyright 1999-2022 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.17.0

EAPI=8

DIST_AUTHOR="CAPOEIRAB"
DIST_VERSION="3.16"


inherit perl-module

DESCRIPTION="Encoding and decoding of base64 strings"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64 ~x86 "
IUSE=""

DEPEND="dev-lang/perl"
